### ISSUE TITLE
About train data .npy

### ISSUE THREAD

**Issue by lkyee** [Zheng222/IDN-tensorflow#1]
Hi
Thanks for your code.I want to know how to generate .npy file.

**Comment by Zheng222** [comment]
@lkyee Hello, please see the following code snippet.
https://github.com/Zheng222/IDN-tensorflow/blob/2a3012360a172ef6b8c8fc99caf7d4ad83850c10/train_SR.py#L36-L46

**Comment by lkyee** [comment]
Thanks for your kind reply！
I try to use the train set DIV2K,but cause the memory error.And if i use the train set of 291,it is fine.
Could you tell me what can I do to solve the problem? Thank you!

**Comment by lkyee** [comment]
Creating data binary...
Traceback (most recent call last):
  File "D:/MyIDN_conv+db4_rgb/train_SR.py", line 54, in <module>
    np.save(train_hr_npy, train_hr_imgs)
  File "E:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\numpy\lib\npyio.py", line 521, in save
    pickle_kwargs=pickle_kwargs)
  File "E:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\numpy\lib\format.py", line 593, in write_array
    pickle.dump(array, fp, protocol=2, **pickle_kwargs)
MemoryError

**Comment by Zheng222** [comment]
Is it due to insufficient memory?

**Comment by lkyee** [comment]
是的，我用了实验室的服务器了，内存也有64g，但还是报错了，有没有不那么占内存的处理方法？谢谢了！

**Comment by Zheng222** [comment]
You can refer to [tensorflow official pix2pix code](https://github.com/tensorflow/tensorflow/blob/r1.13/tensorflow/contrib/eager/python/examples/pix2pix/pix2pix_eager.ipynb).

**Comment by wujiexiaowugui** [comment]
I hanve met the same issue. Do you solve this problem?

**Comment by lkyee** [comment]
Yes.I just comment the code like
#np.save(train_hr_npy, train_hr_imgs)
you can try it

**Comment by chensiyu1120** [comment]
> 是的， 我只是评论代码，如#np. 保存 （train_hr_npy， train_hr_imgs），你可以尝试一下

你好，打扰您了，我想问一下您有咩有出现这个问题
Caused by op 'IDN/conv1/Conv2D', defined at:
  File "train_SR.py", line 54, in <module>
    tensor_sr = IDN(tensor_lr, tensor_b, scale)
  File "/data1/home/chensiyu/IDN-tensorflow-master/model.py", line 6, in IDN
    conv1 = tf.layers.conv2d(t_image, 64, (3, 3), (1, 1), padding='same', activation=lrelu, name='conv1')
ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[16,64,96,96] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node IDN/conv1/Conv2D}} = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/IDN/conv1/Conv2D_grad/Conv2DBackpropFilter-0-TransposeNHWCToNCHW-LayoutOptimizer, IDN/conv1/kernel/read)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[{{node Mean/_403}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3662_Mean", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

**Comment by Zheng222** [comment]
> 
> 
> 
> 
> > 是的， 我只是评论代码，如#np. 保存 （train_hr_npy， train_hr_imgs），你可以尝试一下
> 
> 你好，打扰您了，我想问一下您有咩有出现这个问题
> Caused by op 'IDN/conv1/Conv2D', defined at:
>   File "train_SR.py", line 54, in <module>
>     tensor_sr = IDN(tensor_lr, tensor_b, scale)
>   File "/data1/home/chensiyu/IDN-tensorflow-master/model.py", line 6, in IDN
>     conv1 = tf.layers.conv2d(t_image, 64, (3, 3), (1, 1), padding='same', activation=lrelu, name='conv1')
> ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[16,64,96,96] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
> 	 [[{{node IDN/conv1/Conv2D}} = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/IDN/conv1/Conv2D_grad/Conv2DBackpropFilter-0-TransposeNHWCToNCHW-LayoutOptimizer, IDN/conv1/kernel/read)]]
> Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
> 
> 	 [[{{node Mean/_403}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3662_Mean", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
> Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
> 
> 

我没有遇到这个问题，IDN-tensorflow已经很久没有维护了，推荐使用README中的tf版本运行。也可以看一下IMDN，这个是用pytorch实现的，更简单。

**Comment by chensiyu1120** [comment]
您好，我现在正在训练IDN，解决了那个问题，现在同时在做IMDN的环境准备工作。谢谢您的回复。


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "Zheng222/IDN-tensorflow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月11日(星期四) 下午5:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Zheng222/IDN-tensorflow] About train data .npy (#1)





   
是的， 我只是评论代码，如#np. 保存 （train_hr_npy， train_hr_imgs），你可以尝试一下
  
你好，打扰您了，我想问一下您有咩有出现这个问题
 Caused by op 'IDN/conv1/Conv2D', defined at:
 File "train_SR.py", line 54, in 
 tensor_sr = IDN(tensor_lr, tensor_b, scale)
 File "/data1/home/chensiyu/IDN-tensorflow-master/model.py", line 6, in IDN
 conv1 = tf.layers.conv2d(t_image, 64, (3, 3), (1, 1), padding='same', activation=lrelu, name='conv1')
 ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[16,64,96,96] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
 [[{{node IDN/conv1/Conv2D}} = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/IDN/conv1/Conv2D_grad/Conv2DBackpropFilter-0-TransposeNHWCToNCHW-LayoutOptimizer, IDN/conv1/kernel/read)]]
 Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
 
[[{{node Mean/_403}} = _Recvclient_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3662_Mean", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]]
 Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
  
我没有遇到这个问题，IDN-tensorflow已经很久没有维护了，推荐使用README中的tf版本运行。也可以看一下IMDN，这个是用pytorch实现的，更简单。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
